### ISSUE TITLE
sort by or color free/paid

### ISSUE THREAD

**Issue by jonmarkprice** [javascript-society/javascript-path#17]
As a incorrigible cheapskate I'd like a way to easily visually distinguish between the free/paid books. I know it's not possible to change the colors on markdown, but you could attach an SVG. I made some with Inkscape, feel free to edit.
https://github.com/jonmarkprice/misc/blob/master/free.svg
https://github.com/jonmarkprice/misc/blob/master/paid.svg
 
Another idea would be to use emoji :free: `free` and :heavy_dollar_sign: `heavy_dollar_sign`.

**Comment by ericdouglas** [comment]
@jonmarkprice 

I updated the README file with your suggestion! Thank you very much :smile:
