### ISSUE TITLE
Functional JS Book Suggestion: Programming JavaScript Applications (2014)

### ISSUE THREAD

**Issue by janaipakos** [javascript-society/javascript-path#20]
[Programming JavaScript Applications](http://shop.oreilly.com/product/0636920033141.do) by Eric Elliot.

Prototypal OO and functional programming.

**Comment by BalbuenaJuan** [comment]
I vote for this book

**Comment by ericdouglas** [comment]
:+1: 

ps: This books fits in the "Node path" as well. :smile:

**Comment by janaipakos** [comment]
@ericdouglas is there a WiP list for the Node.js path?

**Comment by TvrtkoM** [comment]
:+1:

**Comment by manzettidenis** [comment]
Guys, this book have a free version online: http://chimera.labs.oreilly.com/books/1234000000262/index.html
