### ISSUE TITLE
Companion Sites

### ISSUE THREAD

**Issue by snlacks** [javascript-society/javascript-path#30]
Some of the books (paid and free) have free companion sites that are pretty useful. It might be worth adding a column or parenthetical for this. One I know is Secrets of a JavaScript Ninja has live demos at http://ejohn.org/apps/learn/

Thanks for the list.

**Comment by ericdouglas** [comment]
@snlacks thank you for your suggestion, but I think this one is an exception. Other books don't have such type of complement.

Furthermore, we are trying to stay only with book indications here too, for that reason I think that such kind of resources doesn't fit too well on this list.

Anyway, thanks again for your contribution! :smile:

**Comment by snlacks** [comment]
Understood, thank you.

**Comment by ericdouglas** [comment]
:beers:
