### ISSUE TITLE
JavaScript Patterns Book Suggestion

### ISSUE THREAD

**Issue by bmkmanoj** [javascript-society/javascript-path#32]
[JavaScript Patterns](http://www.amazon.com/JavaScript-Patterns-Stoyan-Stefanov/dp/0596806752/ref=sr_1_1?ie=UTF8&qid=1453401713&sr=8-1&keywords=javascript+patterns) by Stoyan Stefanov.

Understanding of commonly used JS patterns used across the community.

**Comment by TvrtkoM** [comment]
:+1:

**Comment by ericdouglas** [comment]
:+1:

**Comment by EoghainC** [comment]
Good book
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by helton** [comment]
:+1:
