### ISSUE TITLE
Functional programming - more specialized material

### ISSUE THREAD

**Issue by cbelden** [javascript-society/javascript-path#4]
Hello!

I briefly went over the index for *JavaScript Allonge*, and it seems to be more of a general purpose JavaScript text than a functional programming guide. Would it be possible to add a functional programming text that is more focused?

Thanks

**Comment by molant** [comment]
I have in my library [Functional JavaScript](http://www.amazon.com/Functional-JavaScript-Introducing-Programming-Underscore-js/dp/1449360726). Although it uses underscore for some of the examples in most cases is library agnostic.
Haven't read JavaScript Allongé yet

**Comment by ericdouglas** [comment]
@cbelden 

this book was suggested [here](http://jugoncalv.es/blog/javascript/how-to-start-with-javascript/), and the author of this post know a bunch about FP.

But we have [this](https://github.com/MostlyAdequate/mostly-adequate-guide) book about FP too.

I'm thinking in a way to add an additional resources section.

:smile:
