### ISSUE TITLE
Update "How to use this list" section

### ISSUE THREAD

**Issue by ericdouglas** [javascript-society/javascript-path#7]

**Comment by vitaliyterziev** [comment]
I am sorry to say that but the list is complete disaster and the "use list" is the worst

**Comment by ericdouglas** [comment]
@vitaliyterziev 

thank you for your feedback!

But sadly I can't convert this to a useful improvement here.

You're welcome to send concrete suggestions to improve this path :smile:

**Comment by vitaliyterziev** [comment]
@ericdouglas , Apologies for my first comment. "Start with the first book, and after finish it, go down to the next one. Repeat this process until you finish all books. :smile:" - > this sentence is not constructive and bad, if you are going to advise reading top to bottom the first one should be JavaScript: The Definitive Guide, 6th Edition followed by Eloquent JavaScript (which is not the very "basic" reading) and in this manner, JavaScript Application Design is far from novice reading. In my opinion the last one should be removed and not used to teach people JS.

**Comment by ericdouglas** [comment]
@vitaliyterziev thank you for pointing out your opinion.

The "Additional Resources" don't need to be read in the exact order, you can pick whatever book that you want to read, without a strict order.

I'll state this when I update this section, for that reason I opened this issue.

About the JavaScript Application Design, the book assumes that readers understand the basics of JavaScript.

**Comment by vitaliyterziev** [comment]
@ericdouglas, thanks for the explanation. My only concern was that one could assume that the list is ordered based on the "use list" (i did :D). Some of the tifles are really good, in my opinion.
